# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.4
loader_version=0.19.3

# Mod Properties
mod_version = 2.0.28+1.21.11
maven_group=com.khazoda
archives_base_name=basicstorage
mod_id=basicstorage
mod_name=Basic Storage
mod_description=Vanilla-friendly mass item storage
mod_author=Khazoda
mod_homepage=https://khazoda.com#basic-storage
mod_sources=https://github.com/Khazoda/basic-storage
mod_issues=https://github.com/Khazoda/basic-storage/issues
mod_license=MIT
mod_icon=assets/basicstorage/icon.png
main_class=com.khazoda.basicstorage.BasicStorage
client_class=com.khazoda.basicstorage.BasicStorageClient

# Dependencies
fabric_version=0.141.4+1.21.11
fabric_loader_version=0.19.3
loom_version=1.14-SNAPSHOT
java_version=21
